= [[DeltaSource]] DeltaSource -- Streaming Source of Delta Data Source

`DeltaSource` is the source of <<DeltaDataSource.adoc#, delta data source>> for streaming queries in Spark Structured Streaming.

TIP: Read up on https://jaceklaskowski.gitbooks.io/spark-structured-streaming/spark-sql-streaming-Source.html[Streaming Source] in https://bit.ly/spark-structured-streaming[The Internals of Spark Structured Streaming] online book.

```
val q = spark
  .readStream
  .format("delta")
  .load("/tmp/delta/users")
  .writeStream
  .format("memory")
  .option("queryName", "demo")
  .start
import org.apache.spark.sql.execution.streaming.{MicroBatchExecution, StreamingQueryWrapper}
val plan = q.asInstanceOf[StreamingQueryWrapper]
  .streamingQuery
  .asInstanceOf[MicroBatchExecution]
  .logicalPlan
import org.apache.spark.sql.execution.streaming.StreamingExecutionRelation
val relation = plan.collect { case r: StreamingExecutionRelation => r }.head

import org.apache.spark.sql.delta.sources.DeltaSource
assert(relation.source.asInstanceOf[DeltaSource])

scala> println(relation.source)
DeltaSource[file:/tmp/delta/users]
```

[[maxFilesPerTrigger]]
`DeltaSource` uses <<DeltaOptions.adoc#maxFilesPerTrigger, maxFilesPerTrigger>> option to limit the number of files added when requested for the <<getChangesWithRateLimit, file additions (with rate limit)>>.

== [[getBatch]] Creating DataFrame For Data Between Start And End Offsets -- `getBatch` Method

[source, scala]
----
getBatch(
  start: Option[Offset],
  end: Offset): DataFrame
----

NOTE: `getBatch` is part of the `Source` contract (Spark Structured Streaming) for a streaming `DataFrame` with data between the start and end offsets.

`getBatch` creates an `DeltaSourceOffset` for the <<tableId, tableId>> and the given `end` offset.

`getBatch` <<getChanges, gets the changes>> as follows...FIXME

== [[getOffset]] Retrieving Latest Offset -- `getOffset` Method

[source, scala]
----
getOffset: Option[Offset]
----

NOTE: `getOffset` is part of the streaming `Source` contract (Spark Structured Streaming) to retrieve the latest available offset for this source.

`getOffset`...FIXME

== [[stop]] Stopping Streaming Source -- `stop` Method

[source, scala]
----
stop(): Unit
----

NOTE: `stop` is part of the streaming `Source` contract (Spark Structured Streaming) to stop this source and free up any resources allocated.

`stop` simply <<cleanUpSnapshotResources, cleanUpSnapshotResources>>.

== [[getStartingOffset]] Retrieving Starting Offset -- `getStartingOffset` Internal Method

[source, scala]
----
getStartingOffset(): Option[Offset]
----

`getStartingOffset` requests the <<deltaLog, DeltaLog>> for the version of the delta table (by requesting for the <<DeltaLog.adoc#snapshot, current state (snapshot)>> and then for the <<Snapshot.adoc#version, version>>).

`getStartingOffset` <<iteratorLast, takes the last file>> from the <<getChangesWithRateLimit, files added (with rate limit)>> for the version of the delta table, `-1L` as the `fromIndex`, and the `isStartingVersion` flag enabled (`true`).

`getStartingOffset` returns a new <<DeltaSourceOffset.adoc#, DeltaSourceOffset>> for the <<tableId, tableId>>, the version and the index of the last file added, and whether the last file added is the last file of its version.

`getStartingOffset` returns `None` (_offset not available_) when either happens:

* the version of the delta table is negative (below `0`)

* no files were added in the version

`getStartingOffset` throws an `AssertionError` when the version of the last file added is smaller than the delta table's version:

```
assertion failed: getChangesWithRateLimit returns an invalid version: [v] (expected: >= [version])
```

NOTE: `getStartingOffset` is used exclusively when `DeltaSource` is requested to <<getOffset, getOffset>>.

== [[getChanges]] `getChanges` Internal Method

[source, scala]
----
getChanges(
  fromVersion: Long,
  fromIndex: Long,
  isStartingVersion: Boolean): Iterator[IndexedFile]
----

`getChanges` branches per the given `isStartingVersion` flag:

* When enabled (`true`), `getChanges` <<getSnapshotAt, gets the state (snapshot)>> for the given `fromVersion`...FIXME

NOTE: `getChanges` is used when `DeltaSource` is requested for the <<getChangesWithRateLimit, files added (with rate limit)>> and <<getBatch, getBatch>>.

== [[getChangesWithRateLimit]] Retrieving File Additions (With Rate Limit) -- `getChangesWithRateLimit` Internal Method

[source, scala]
----
getChangesWithRateLimit(
  fromVersion: Long,
  fromIndex: Long,
  isStartingVersion: Boolean): Iterator[IndexedFile]
----

`getChangesWithRateLimit` <<getChanges, get the changes>> (as indexed <<AddFile.adoc#, AddFiles>>) for the given `fromVersion`, `fromIndex`, and `isStartingVersion` flag.

`getChangesWithRateLimit` takes the configured number of `AddFiles` (up to the <<maxFilesPerTrigger, maxFilesPerTrigger>> option (if defined) or <<DeltaOptions.adoc#MAX_FILES_PER_TRIGGER_OPTION_DEFAULT, 1000>>).

NOTE: `getChangesWithRateLimit` is used when `DeltaSource` is requested to <<getStartingOffset, getStartingOffset>> and <<getOffset, getOffset>>.

== [[getSnapshotAt]] Retrieving State Of Delta Table At Given Version -- `getSnapshotAt` Internal Method

[source, scala]
----
getSnapshotAt(
  version: Long): Iterator[IndexedFile]
----

`getSnapshotAt` requests the <<initialState, DeltaSourceSnapshot>> for the <<SnapshotIterator.adoc#iterator, data files>> (as indexed <<AddFile.adoc#, AddFiles>>).

In case the <<initialState, DeltaSourceSnapshot>> hasn't been initialized yet (`null`) or the requested version is different from the <<initialStateVersion, initialStateVersion>>, `getSnapshotAt` does the following:

. <<cleanUpSnapshotResources, cleanUpSnapshotResources>>

. Requests the <<deltaLog, DeltaLog>> for the <<DeltaLog.adoc#getSnapshotAt, state (snapshot) of the delta table>> at the version

. Creates a new <<DeltaSourceSnapshot.adoc#, DeltaSourceSnapshot>> for the state (snapshot) as the current <<initialState, DeltaSourceSnapshot>>

. Changes the <<initialStateVersion, initialStateVersion>> internal registry to the requested version

NOTE: `getSnapshotAt` is used when `DeltaSource` is requested to <<getChanges, getChanges>> (with `isStartingVersion` flag enabled).

== [[verifyStreamHygieneAndFilterAddFiles]] `verifyStreamHygieneAndFilterAddFiles` Internal Method

[source, scala]
----
verifyStreamHygieneAndFilterAddFiles(
  actions: Seq[Action]): Seq[Action]
----

`verifyStreamHygieneAndFilterAddFiles`...FIXME

NOTE: `verifyStreamHygieneAndFilterAddFiles` is used when `DeltaSource` is requested to <<getChanges, getChanges>>.

== [[cleanUpSnapshotResources]] `cleanUpSnapshotResources` Internal Method

[source, scala]
----
cleanUpSnapshotResources(): Unit
----

`cleanUpSnapshotResources`...FIXME

NOTE: `cleanUpSnapshotResources` is used when `DeltaSource` is requested to <<getSnapshotAt, getSnapshotAt>>, <<getBatch, getBatch>> and <<stop, stop>>.

== [[iteratorLast]] Retrieving Last Element From Iterator -- `iteratorLast` Internal Method

[source, scala]
----
iteratorLast[T](
  iter: Iterator[T]): Option[T]
----

`iteratorLast` simply returns the last element in the given `Iterator` or `None`.

NOTE: `iteratorLast` is used when `DeltaSource` is requested to <<getStartingOffset, getStartingOffset>> and <<getOffset, getOffset>>.

== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| initialState
a| [[initialState]] <<DeltaSourceSnapshot.adoc#, DeltaSourceSnapshot>>

Initially uninitialized (`null`).

Changes (along with the <<initialStateVersion, initialStateVersion>>) when `DeltaSource` is requested for the <<getSnapshotAt, snapshot at a given version>> (only when the versions are different)

Used when `DeltaSource` is requested for the <<getSnapshotAt, snapshot at a given version>>

Closed and dereferenced (`null`) when `DeltaSource` is requested to <<cleanUpSnapshotResources, cleanUpSnapshotResources>>

| initialStateVersion
a| [[initialStateVersion]] Version of the <<deltaLog, delta table>>

Initially `-1L` and changes (along with the <<initialState, initialState>>) to the version requested when `DeltaSource` is requested for the <<getSnapshotAt, snapshot at a given version>> (only when the versions are different)

Used when `DeltaSource` is requested to <<cleanUpSnapshotResources, cleanUpSnapshotResources>> (and unpersist the current snapshot)

| tableId
a| [[tableId]] Table ID

Used when...FIXME

|===
