= [[DeltaSource]] DeltaSource -- Streaming Source of Delta Data Source

`DeltaSource` is the source of <<DeltaDataSource.adoc#, delta data source>> for streaming queries in Spark Structured Streaming.

TIP: Read up on https://jaceklaskowski.gitbooks.io/spark-structured-streaming/spark-sql-streaming-Source.html[Streaming Source] in https://bit.ly/spark-structured-streaming[The Internals of Spark Structured Streaming] online book.

== [[getBatch]] Creating DataFrame For Data Between Start And End Offsets -- `getBatch` Method

[source, scala]
----
getBatch(
  start: Option[Offset],
  end: Offset): DataFrame
----

NOTE: `getBatch` is part of the `Source` contract (Spark Structured Streaming) to...FIXME.

`getBatch`...FIXME

== [[getOffset]] `getOffset` Method

[source, scala]
----
getOffset: Option[Offset]
----

NOTE: `getOffset` is part of the streaming `Source` contract (Spark Structured Streaming) to get the maximum available offset for this source.

`getOffset`...FIXME

== [[stop]] Stopping Streaming Source -- `stop` Method

[source, scala]
----
stop(): Unit
----

NOTE: `stop` is part of the streaming `Source` contract (Spark Structured Streaming) to stop this source and free up any resources allocated.

`stop` simply <<cleanUpSnapshotResources, cleanUpSnapshotResources>>.

== [[getStartingOffset]] `getStartingOffset` Internal Method

[source, scala]
----
getStartingOffset(): Option[Offset]
----

`getStartingOffset`...FIXME

NOTE: `getStartingOffset` is used exclusively when `DeltaSource` is requested to <<getOffset, getOffset>>.

== [[getChangesWithRateLimit]] `getChangesWithRateLimit` Internal Method

[source, scala]
----
getChangesWithRateLimit(
  fromVersion: Long,
  fromIndex: Long,
  isStartingVersion: Boolean): Iterator[IndexedFile]
----

`getChangesWithRateLimit`...FIXME

NOTE: `getChangesWithRateLimit` is used when `DeltaSource` is requested to <<getStartingOffset, getStartingOffset>> and <<getOffset, getOffset>>.

== [[getChanges]] `getChanges` Internal Method

[source, scala]
----
getChanges(
  fromVersion: Long,
  fromIndex: Long,
  isStartingVersion: Boolean): Iterator[IndexedFile]
----

`getChanges`...FIXME

NOTE: `getChanges` is used when `DeltaSource` is requested to <<getChangesWithRateLimit, getChangesWithRateLimit>> and <<getBatch, getBatch>>.

== [[getSnapshotAt]] Looking Up Snapshot By Version -- `getSnapshotAt` Internal Method

[source, scala]
----
getSnapshotAt(
  version: Long): Iterator[IndexedFile]
----

`getSnapshotAt`...FIXME

NOTE: `getSnapshotAt` is used when `DeltaSource` is requested to <<getChanges, getChanges>>.

== [[verifyStreamHygieneAndFilterAddFiles]] `verifyStreamHygieneAndFilterAddFiles` Internal Method

[source, scala]
----
verifyStreamHygieneAndFilterAddFiles(
  actions: Seq[Action]): Seq[Action]
----

`verifyStreamHygieneAndFilterAddFiles`...FIXME

NOTE: `verifyStreamHygieneAndFilterAddFiles` is used when `DeltaSource` is requested to <<getChanges, getChanges>>.

== [[cleanUpSnapshotResources]] `cleanUpSnapshotResources` Internal Method

[source, scala]
----
cleanUpSnapshotResources(): Unit
----

`cleanUpSnapshotResources`...FIXME

NOTE: `cleanUpSnapshotResources` is used when `DeltaSource` is requested to <<getSnapshotAt, getSnapshotAt>>, <<getBatch, getBatch>> and <<stop, stop>>.
