= InMemoryLogReplay

`InMemoryLogReplay` is used for <<Snapshot.adoc#stateReconstruction, state reconstruction>> (of the <<Snapshot.adoc#cachedState, cached delta state>>).

`InMemoryLogReplay` is <<creating-instance, created>> for every partition of the <<Snapshot.adoc#stateReconstruction, stateReconstruction>> dataset (`Dataset[SingleAction]`) that is based on the <<DeltaSQLConf.adoc#DELTA_SNAPSHOT_PARTITIONS, spark.databricks.delta.snapshotPartitions>> configuration property (default: `50`).

== [[creating-instance]] Creating InMemoryLogReplay Instance

`InMemoryLogReplay` takes the following to be created:

* [[minFileRetentionTimestamp]] `minFileRetentionTimestamp` (that is exactly <<Snapshot.adoc#minFileRetentionTimestamp, Snapshot.minFileRetentionTimestamp>>)

`InMemoryLogReplay` initializes the <<internal-properties, internal properties>>.

== [[append]] `append` Method

[source, scala]
----
append(
  version: Long,
  actions: Iterator[Action]): Unit
----

`append`...FIXME

NOTE: `append` is used when `Snapshot` is created (and initializes the <<Snapshot.adoc#stateReconstruction, stateReconstruction>> for the <<Snapshot.adoc#cachedState, cached delta state>>).

== [[checkpoint]] Current State Of Delta Table -- `checkpoint` Method

[source, scala]
----
checkpoint: Iterator[Action]
----

`checkpoint`...FIXME

NOTE: `checkpoint` is used when `Snapshot` is created (and initializes the <<Snapshot.adoc#stateReconstruction, stateReconstruction>> for the <<Snapshot.adoc#cachedState, cached delta state>>).

== [[getTombstones]] `getTombstones` Internal Method

[source, scala]
----
getTombstones: Iterable[FileAction]
----

`getTombstones`...FIXME

NOTE: `getTombstones` is used when `InMemoryLogReplay` is requested to <<checkpoint, checkpoint>>.

== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| currentProtocolVersion
a| [[currentProtocolVersion]] <<Protocol.adoc#, Protocol>> (default: `null`)

Used when...FIXME

| currentVersion
a| [[currentVersion]] Version (default: `-1`)

Used when...FIXME

| currentMetaData
a| [[currentMetaData]] <<Metadata.adoc#, Metadata>> (default: `null`)

Used when...FIXME

| transactions
a| [[transactions]] <<SetTransaction.adoc#, SetTransactions>> per ID (`HashMap[String, SetTransaction]`)

Used when...FIXME

| activeFiles
a| [[activeFiles]] <<FileAction.adoc.adoc#AddFile, AddFile>> per URI (`HashMap[URI, AddFile]`)

Used when...FIXME

| tombstones
a| [[tombstones]] <<FileAction.adoc.adoc#RemoveFile, RemoveFile>> per URI (`HashMap[URI, RemoveFile]`)

Used when...FIXME

|===
