= MergeIntoCommand

MergeIntoCommand is a <<DeltaCommand.adoc#, Delta command>> that can...FIXME

MergeIntoCommand is a logical command (`RunnableCommand`).

TIP: Read up on https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-LogicalPlan-RunnableCommand.html[RunnableCommand] in https://bit.ly/spark-sql-internals[The Internals of Spark SQL] online book.

MergeIntoCommand is <<creating-instance, created>> exclusively when `DeltaMergeBuilder` is requested to <<DeltaMergeBuilder.adoc#execute, execute>> (using <<PreprocessTableMerge.adoc#apply, PreprocessTableMerge>>).

== [[creating-instance]] Creating MergeIntoCommand Instance

MergeIntoCommand takes the following to be created:

* [[source]] Source Data (`LogicalPlan`)
* [[target]] Target Data (`LogicalPlan`)
* [[targetFileIndex]] <<TahoeFileIndex.adoc#, TahoeFileIndex>>
* [[condition]] Condition (`Expression`)
* [[matchedClauses]] Matched Clauses (`Seq[MergeIntoMatchedClause]`)
* [[notMatchedClause]] Non-Matched Clauses (`Option[MergeIntoInsertClause]`)

MergeIntoCommand initializes the <<internal-properties, internal properties>>.

== [[run]] Running Command -- `run` Method

[source, scala]
----
run(spark: SparkSession): Seq[Row]
----

NOTE: `run` is part of the `RunnableCommand` contract to...FIXME.

`run`...FIXME

== [[writeAllChanges]] `writeAllChanges` Internal Method

[source, scala]
----
writeAllChanges(
  spark: SparkSession,
  deltaTxn: OptimisticTransaction,
  filesToRewrite: Seq[AddFile]): Seq[AddFile]
----

`writeAllChanges`...FIXME

NOTE: `writeAllChanges` is used exclusively when MergeIntoCommand is requested to <<run, run>>.

== [[findTouchedFiles]] `findTouchedFiles` Internal Method

[source, scala]
----
findTouchedFiles(
  deltaTxn: OptimisticTransaction,
  files: Seq[AddFile]): LogicalPlan
----

`findTouchedFiles`...FIXME

NOTE: `findTouchedFiles` is used when MergeIntoCommand is requested to <<run, run>>.

== [[buildTargetPlanWithFiles]] `buildTargetPlanWithFiles` Internal Method

[source, scala]
----
buildTargetPlanWithFiles(
  deltaTxn: OptimisticTransaction,
  files: Seq[AddFile]): LogicalPlan
----

`buildTargetPlanWithFiles`...FIXME

NOTE: `buildTargetPlanWithFiles` is used when MergeIntoCommand is requested to <<run, run>> (via <<findTouchedFiles, findTouchedFiles>> and <<writeAllChanges, writeAllChanges>>).
