= [[OptimisticTransactionImpl]] OptimisticTransactionImpl

`OptimisticTransactionImpl` is an <<contract, extension>> of the <<TransactionalWrite.adoc#, TransactionalWrite contract>> for <<implementations, optimistic transactions>> that can be <<commit, committed>>.

[[contract]]
.OptimisticTransactionImpl Contract (Abstract Methods Only)
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| deltaLog
a| [[deltaLog]]

[source, scala]
----
deltaLog: DeltaLog
----

<<DeltaLog.adoc#, DeltaLog>> of a delta table

NOTE: `deltaLog` is part of the <<TransactionalWrite.adoc#deltaLog, TransactionalWrite>> contract and seems to change it to `val` (from `def`).

| snapshot
a| [[snapshot]]

[source, scala]
----
snapshot: Snapshot
----

<<Snapshot.adoc#, Snapshot>> of a delta table

NOTE: `snapshot` is part of the <<TransactionalWrite.adoc#snapshot, TransactionalWrite>> contract and seems to change it to `val` (from `def`).

|===

[[implementations]]
NOTE: <<OptimisticTransaction.adoc#, OptimisticTransaction>> is the only known `OptimisticTransactionImpl` in Delta Lake.

== [[postCommitHooks]] Post-Commit Hooks -- `postCommitHooks` Internal Registry

[source, scala]
----
postCommitHooks: ArrayBuffer[PostCommitHook]
----

`OptimisticTransactionImpl` manages <<PostCommitHook.adoc#, post-commit hooks>> that will be <<runPostCommitHooks, executed>> after a <<commit, commit>> is successful.

Post-commit hooks can be <<registerPostCommitHook, registered>>, but only the <<GenerateSymlinkManifest.adoc#, GenerateSymlinkManifest>> post-commit hook is supported (when...FIXME).

== [[newMetadata]] `newMetadata` Internal Registry

[source, scala]
----
newMetadata: Option[Metadata]
----

`OptimisticTransactionImpl` uses the `newMetadata` internal registry for a new <<Metadata.adoc#, Metadata>> that should be committed with this transaction.

`newMetadata` is initially undefined (`None`). It can be <<updateMetadata, updated>> only once and before the transaction <<TransactionalWrite.adoc#hasWritten, writes out any files>>.

`newMetadata` is used when <<prepareCommit, prepareCommit>> (and <<doCommit, doCommit>> for statistics).

`newMetadata` is available using <<metadata, metadata>> method.

== [[metadata]] `metadata` Method

[source, scala]
----
metadata: Metadata
----

NOTE: `metadata` is part of the <<TransactionalWrite.adoc#metadata, TransactionalWrite Contract>> to...FIXME.

`metadata` is either the <<newMetadata, newMetadata>> (if defined) or the <<snapshotMetadata, snapshotMetadata>>.

== [[readVersion]] `readVersion` Method

[source, scala]
----
readVersion: Long
----

`readVersion` simply requests the <<snapshot, Snapshot>> for the <<Snapshot.adoc#version, version>>.

[NOTE]
====
`readVersion` is used when:

* `OptimisticTransactionImpl` is requested for <<snapshotMetadata, snapshotMetadata>>, to <<updateMetadata, updateMetadata>> and <<commit, commit>>

* `ConvertToDeltaCommand` is requested to <<ConvertToDeltaCommand.adoc#run, run>>

* `WriteIntoDelta` is requested to <<WriteIntoDelta.adoc#write, write>>

* `ImplicitMetadataOperation` is requested to <<ImplicitMetadataOperation.adoc#updateMetadata, updateMetadata>>
====

== [[updateMetadata]] Updating Metadata -- `updateMetadata` Method

[source, scala]
----
updateMetadata(
  metadata: Metadata): Unit
----

`updateMetadata` updates the <<newMetadata, newMetadata>> internal property based on the <<readVersion, readVersion>>:

* For `-1`, `updateMetadata` updates the <<Metadata.adoc#configuration, configuration>> of the given `Metadata` with a <<DeltaConfigs.adoc#mergeGlobalConfigs, new metadata>> based on the `SQLConf` (of the active `SparkSession`), the <<Metadata.adoc#configuration, configuration>> of the given `Metadata` and a new <<Protocol.adoc#, Protocol>>

* For other versions, `updateMetadata` leaves the given <<Action.adoc#Metadata, Metadata>> unchanged

[[updateMetadata-AssertionError-hasWritten]]
`updateMetadata` throws an `AssertionError` when the <<TransactionalWrite.adoc#hasWritten, hasWritten>> flag is enabled (`true`):

```
Cannot update the metadata in a transaction that has already written data.
```

`updateMetadata` throws an `AssertionError` when the <<newMetadata, newMetadata>> is not empty:

```
Cannot change the metadata more than once in a transaction.
```

[NOTE]
====
`updateMetadata` is used when:

* <<ConvertToDeltaCommand.adoc#, ConvertToDeltaCommand>> is executed (and requested to <<ConvertToDeltaCommand.adoc#performConvert, performConvert>>)

* `ImplicitMetadataOperation` is requested to <<ImplicitMetadataOperation.adoc#updateMetadata, updateMetadata>>
====

== [[filterFiles]] `filterFiles` Method

[source, scala]
----
filterFiles(): Seq[AddFile]
filterFiles(
  filters: Seq[Expression]): Seq[AddFile]
----

`filterFiles`...FIXME

NOTE: `filterFiles` is used when...FIXME

== [[readWholeTable]] `readWholeTable` Method

[source, scala]
----
readWholeTable(): Unit
----

`readWholeTable`...FIXME

NOTE: `readWholeTable` is used when...FIXME

== [[commit]] Committing Transaction -- `commit` Method

[source, scala]
----
commit(
  actions: Seq[Action],
  op: DeltaOperations.Operation): Long
----

[[commit-prepareCommit]]
`commit` firstly <<prepareCommit, prepares a commit>> (that gives the final actions to commit that may be different from the given <<Action.adoc#, actions>>).

[[commit-isolationLevelToUse]]
`commit` determines the isolation level for this commit by checking whether any <<FileAction.adoc#, FileAction>> (in the given <<Action.adoc#, actions>>) has the <<FileAction.adoc#dataChange, dataChange>> flag on (`true`). With no data changed, `commit` uses `SnapshotIsolation` else `Serializable`.

[[commit-isBlindAppend]]
`commit`...FIXME

[[commit-commitInfo]]
`commit`...FIXME

[[commit-registerPostCommitHook]]
`commit` <<registerPostCommitHook, registers>> the <<GenerateSymlinkManifest.adoc#, GenerateSymlinkManifest>> post-commit hook when there is a <<FileAction.adoc#, FileAction>> among the actions and the <<DeltaConfigs.adoc#SYMLINK_FORMAT_MANIFEST_ENABLED, compatibility.symlinkFormatManifest.enabled>> table property (<<DeltaConfigs.adoc#fromMetaData, from>> the <<metadata, Metadata>>) is enabled (`true`).

NOTE: <<DeltaConfigs.adoc#SYMLINK_FORMAT_MANIFEST_ENABLED, compatibility.symlinkFormatManifest.enabled>> table property defaults to `false`.

[[commit-commitVersion]]
`commit` <<doCommit, doCommit>> with the next version, the actions, attempt number `0`, and the select isolation level.

`commit` prints out the following INFO message to the logs:

```
Committed delta #[commitVersion] to [logPath]
```

[[commit-postCommit]]
`commit` <<postCommit, postCommit>> (with the version committed and the actions).

[[commit-runPostCommitHooks]]
In the end, `commit` <<runPostCommitHooks, runs post-commit hooks>> and returns the version of the successful commit.

[NOTE]
====
`commit` is used when:

* `DeltaLog` is requested to <<DeltaLog.adoc#upgradeProtocol, upgradeProtocol>>

* <<DeleteCommand.adoc#, DeleteCommand>>, <<MergeIntoCommand.adoc#, MergeIntoCommand>>, <<UpdateCommand.adoc#, UpdateCommand>>, and <<WriteIntoDelta.adoc#, WriteIntoDelta>> are executed

* `DeltaSink` is requested to <<DeltaSink.adoc#addBatch, addBatch>>
====

== [[prepareCommit]] Preparing Commit -- `prepareCommit` Method

[source, scala]
----
prepareCommit(
  actions: Seq[Action],
  op: DeltaOperations.Operation): Seq[Action]
----

`prepareCommit` adds the <<newMetadata, newMetadata>> action (if available) to the given <<Action.adoc#, actions>>.

`prepareCommit` <<verifyNewMetadata, verifyNewMetadata>> if there was one.

`prepareCommit`...FIXME

`prepareCommit` requests the <<deltaLog, DeltaLog>> to <<DeltaLog.adoc#protocolWrite, protocolWrite>>.

`prepareCommit`...FIXME

`prepareCommit` throws an `AssertionError` when the number of metadata changes in the transaction (by means of <<Action.adoc#Metadata, Metadata>> actions) is above `1`:

```
Cannot change the metadata more than once in a transaction.
```

`prepareCommit` throws an `AssertionError` when the <<committed, committed>> internal flag is turned on (`true`):

```
Transaction already committed.
```

NOTE: `prepareCommit` is used exclusively when `OptimisticTransactionImpl` is requested to <<commit, commit>> (at the beginning).

== [[postCommit]] Performing Post-Commit Operations -- `postCommit` Method

[source, scala]
----
postCommit(
  commitVersion: Long,
  commitActions: Seq[Action]): Unit
----

`postCommit`...FIXME

NOTE: `postCommit` is used exclusively when `OptimisticTransactionImpl` is requested to <<commit, commit>> (at the end).

== [[registerPostCommitHook]] Registering Post-Commit Hook -- `registerPostCommitHook` Method

[source, scala]
----
registerPostCommitHook(
  hook: PostCommitHook): Unit
----

`registerPostCommitHook` registers (_adds_) the given <<PostCommitHook.adoc#, PostCommitHook>> to the <<postCommitHooks, postCommitHooks>> internal registry.

NOTE: `registerPostCommitHook` adds the hook only once.

NOTE: `registerPostCommitHook` is used when `OptimisticTransactionImpl` is requested to <<commit, commit>> (to register the <<GenerateSymlinkManifest.adoc#, GenerateSymlinkManifest>> post-commit hook).

== [[runPostCommitHooks]] Running Post-Commit Hooks -- `runPostCommitHooks` Method

[source, scala]
----
runPostCommitHooks(
  version: Long,
  committedActions: Seq[Action]): Unit
----

`runPostCommitHooks` simply <<PostCommitHook.adoc#run, runs>> every <<PostCommitHook.adoc#, post-commit hook>> registered (in the <<postCommitHooks, postCommitHooks>> internal registry).

`runPostCommitHooks` <<OptimisticTransaction.adoc#clearActive, clears the active transaction>> (making all follow-up operations non-transactional).

NOTE: Hooks may create new transactions.

For any non-fatal exception, `runPostCommitHooks` prints out the following ERROR message to the logs, records the delta event, and requests the post-commit hook to <<PostCommitHook.adoc#handleError, handle the error>>.

```
Error when executing post-commit hook [name] for commit [version]
```

`runPostCommitHooks` throws an `AssertionError` when <<committed, committed>> flag is turned off (`false`):

```
Can't call post commit hooks before committing
```

NOTE: `runPostCommitHooks` is used when `OptimisticTransactionImpl` is requested to <<commit, commit>>.

== [[doCommit]] Attempting Commit -- `doCommit` Internal Method

[source, scala]
----
doCommit(
  attemptVersion: Long,
  actions: Seq[Action],
  attemptNumber: Int): Long
----

`doCommit` returns the given `attemptVersion` as the commit version if successful or <<checkAndRetry, checkAndRetry>>.

Internally, `doCommit` prints out the following DEBUG message to the logs:

```
Attempting to commit version [attemptVersion] with [size] actions with [isolationLevel] isolation level
```

[[doCommit-write]]
`doCommit` requests the <<DeltaLog.adoc#store, LogStore>> (of the <<deltaLog, DeltaLog>>) to <<LogStore.adoc#write, write out>> the given <<Action.adoc#, actions>> (serialized to <<Action.adoc#json, JSON format>>) to a <<FileNames.adoc#deltaFile, delta file>> (e.g. `00000000000000000001.json`) in the <<DeltaLog.adoc#logPath, log directory>> (of the <<deltaLog, DeltaLog>>) with the `attemptVersion` version.

NOTE: <<LogStore.adoc#, LogStores>> must throw a `java.nio.file.FileAlreadyExistsException` exception if the delta file already exists. Any `FileAlreadyExistsExceptions` are caught by <<doCommit-FileAlreadyExistsException, doCommit>> itself to <<checkAndRetry, checkAndRetry>>.

[[doCommit-postCommitSnapshot]]
`doCommit` requests the <<deltaLog, DeltaLog>> to <<DeltaLog.adoc#update, update>>.

[[doCommit-IllegalStateException]]
`doCommit` throws an `IllegalStateException` if the version of the snapshot after update is smaller than the given `attemptVersion` version.

```
The committed version is [attemptVersion] but the current version is [version].
```

[[doCommit-stats]]
`doCommit` records a new `CommitStats` and returns the given `attemptVersion` as the commit version.

[[doCommit-FileAlreadyExistsException]]
`doCommit` catches `FileAlreadyExistsExceptions` and <<checkAndRetry, checkAndRetry>>.

NOTE: `doCommit` is used when `OptimisticTransactionImpl` is requested to <<commit, commit>> (and <<checkAndRetry, checkAndRetry>>).

== [[checkAndRetry]] Retrying Commit -- `checkAndRetry` Internal Method

[source, scala]
----
checkAndRetry(
  checkVersion: Long,
  actions: Seq[Action],
  attemptNumber: Int): Long
----

`checkAndRetry`...FIXME

NOTE: `checkAndRetry` is used when `OptimisticTransactionImpl` is requested to <<commit, commit>> (and <<doCommit, attempts a commit>> that failed with an `FileAlreadyExistsException`).

== [[verifyNewMetadata]] `verifyNewMetadata` Method

[source, scala]
----
verifyNewMetadata(
  metadata: Metadata): Unit
----

`verifyNewMetadata`...FIXME

NOTE: `verifyNewMetadata` is used when `OptimisticTransactionImpl` is requested to <<prepareCommit, prepareCommit>> and <<updateMetadata, updateMetadata>>.

== [[txnVersion]] Looking Up Transaction Version For Given (Streaming Query) ID -- `txnVersion` Method

[source, scala]
----
txnVersion(
  id: String): Long
----

`txnVersion` simply registers (_adds_) the given ID in the <<readTxn, readTxn>> internal registry.

In the end, `txnVersion` requests the <<snapshot, Snapshot>> for the <<Snapshot.adoc#transactions, transaction version for the given ID>> or assumes `-1`.

NOTE: `txnVersion` is used when `DeltaSink` is requested to <<DeltaSink.adoc#addBatch, add a streaming micro-batch>>.

== [[getNextAttemptVersion]] `getNextAttemptVersion` Internal Method

[source, scala]
----
getNextAttemptVersion(
  previousAttemptVersion: Long): Long
----

`getNextAttemptVersion`...FIXME

NOTE: `getNextAttemptVersion` is used when `OptimisticTransactionImpl` is requested to <<checkAndRetry, checkAndRetry>>.

== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| committed
a| [[committed]] Flag that controls whether the transaction is <<commit, committed>> or not (and prevents <<prepareCommit, prepareCommit>> from being executed again)

Default: `false`

Enabled (set to `true`) exclusively in <<postCommit, postCommit>>

| dependsOnFiles
a| [[dependsOnFiles]] Flag that...FIXME

Default: `false`

Enabled (set to `true`) in <<filterFiles, filterFiles>>, <<readWholeTable, readWholeTable>>

Used in <<commit, commit>> and <<checkAndRetry, checkAndRetry>>

| readTxn
a| [[readTxn]] Streaming query IDs that have been seen by this transaction

A new queryId is added when `OptimisticTransactionImpl` is requested for <<txnVersion, txnVersion>>

Used when `OptimisticTransactionImpl` is requested to <<checkAndRetry, checkAndRetry>> (to fail with a `ConcurrentTransactionException` for idempotent transactions that have conflicted)

| snapshotMetadata
a| [[snapshotMetadata]] <<Metadata.adoc#, Metadata>>

|===
