= Options

The following table contains the options of `delta` data source.

The options can be defined using `option` method of `DataFrameReader` and `DataStreamReader`.

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| checkpointLocation
a| [[checkpointLocation]]

| excludeRegex
a| [[excludeRegex]]

| ignoreChanges
a| [[ignoreChanges]]

| ignoreDeletes
a| [[ignoreDeletes]]

| ignoreFileDeletion
a| [[ignoreFileDeletion]]

| maxFilesPerTrigger
a| [[maxFilesPerTrigger]]

| mergeSchema
a| [[mergeSchema]]

| overwriteSchema
a| [[overwriteSchema]]

| optimizeWrite
a| [[optimizeWrite]]

| path
a| [[path]] *(required)* Directory on a Hadoop DFS-compliant file system with an optional <<time-travel.adoc#, time travel>> identifier.

Default: (undefined)

Can also be specified using `load` method of `DataFrameReader` and `DataStreamReader`.

| queryName
a| [[queryName]]

| replaceWhere
a| [[replaceWhere]]

| timestampAsOf
a| [[timestampAsOf]] <<time-travel.adoc#, Time traveling>> using a timestamp of a table

Mutually exclusive with <<versionAsOf, versionAsOf>> option and the time travel identifier of the <<path, path>> option.

| versionAsOf
a| [[versionAsOf]] <<time-travel.adoc#, Time traveling>> using a version of a table

Mutually exclusive with <<timestampAsOf, timestampAsOf>> option and the time travel identifier of the <<path, path>> option.

Used exclusively when `DeltaDataSource` is requested for a <<DeltaDataSource.adoc#RelationProvider-createRelation, relation (as a RelationProvider)>>

|===
