= [[OptimisticTransaction]] OptimisticTransaction

`OptimisticTransaction` is a concrete <<OptimisticTransactionImpl.adoc#, OptimisticTransactionImpl>> (which _seems_ more of a class name change than anything more concrete).

`OptimisticTransaction` is <<creating-instance, created>> when `DeltaLog` is requested to <<DeltaLog.adoc#startTransaction, start a new transaction>> and <<DeltaLog.adoc#withNewTransaction, execute a single-threaded operation in a new transaction>>.

`OptimisticTransaction` can be associated with a thread as an <<active, active transaction>>.

== [[creating-instance]] Creating OptimisticTransaction Instance

`OptimisticTransaction` takes the following to be created:

* [[deltaLog]] <<DeltaLog.adoc#, DeltaLog>>
* [[snapshot]] <<Snapshot.adoc#, Snapshot>> (default: the <<DeltaLog.adoc#snapshot, current snapshot>> of the <<deltaLog, DeltaLog>>)
* [[clock]] `Clock`

NOTE: The <<deltaLog, DeltaLog>> and <<snapshot, Snapshot>> are part of the <<OptimisticTransactionImpl.adoc#, OptimisticTransactionImpl>> contract (which in turn inherits them from the <<TransactionalWrite.adoc#, TransactionalWrite>> contract and changes to `val` from `def`).

== [[active]] Active Thread-Local OptimisticTransaction -- `active` Internal Registry

[source, scala]
----
active: ThreadLocal[OptimisticTransaction]
----

`active` is a Java https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html[ThreadLocal] with the <<OptimisticTransaction.adoc#, OptimisticTransaction>> of the current thread.

> *ThreadLocal* provides thread-local variables. These variables differ from their normal counterparts in that each thread that accesses one (via its get or set method) has its own, independently initialized copy of the variable.

> *ThreadLocal* instances are typically private static fields in classes that wish to associate state with a thread (e.g., a user ID or Transaction ID).

`active` is assigned to the current thread using <<setActive, setActive>> utility and cleared in <<clearActive, clearActive>>.

`active` is available using <<getActive, getActive>> utility.

There can only be one active `OptimisticTransaction` (or an `IllegalStateException` is thrown).

== [[setActive]] `setActive` Utility

[source, scala]
----
setActive(
  txn: OptimisticTransaction): Unit
----

`setActive` simply associates the given `OptimisticTransaction` as <<active, active>> with the current thread.

`setActive` throws an `IllegalStateException` if there is an active `OptimisticTransaction` already associated:

```
Cannot set a new txn as active when one is already active
```

NOTE: `setActive` is used exclusively when `DeltaLog` is requested to <<DeltaLog.adoc#withNewTransaction, execute an operation in a new transaction>>.

== [[clearActive]] `clearActive` Utility

[source, scala]
----
clearActive(): Unit
----

`clearActive` simply clears the <<active, active>> transaction (so no transaction is associated with a thread).

NOTE: `clearActive` is used exclusively when `DeltaLog` is requested to <<DeltaLog.adoc#withNewTransaction, execute an operation in a new transaction>>.

== [[getActive]] `getActive` Utility

[source, scala]
----
getActive(): Option[OptimisticTransaction]
----

`getActive` simply returns the <<active, active>> transaction.

NOTE: `getActive` seems unused.
