= [[Snapshot]] Snapshot

`Snapshot` is <<creating-instance, created>> when `DeltaLog` is requested for the <<DeltaLog.adoc#currentSnapshot, current snapshot>>, to <<DeltaLog.adoc#update, update>>, and <<DeltaLog.adoc#getSnapshotAt, getSnapshotAt>>

== [[creating-instance]] Creating Snapshot Instance

`Snapshot` takes the following to be created:

* [[path]] `Path`
* [[version]] Version
* [[previousSnapshot]] Previous snapshot (`Option[Dataset[SingleAction]]`)
* [[files]] Files (`Seq[Path]`)
* [[minFileRetentionTimestamp]] `minFileRetentionTimestamp`
* [[deltaLog]] <<DeltaLog.adoc#, DeltaLog>>
* [[timestamp]] Timestamp
* [[lineageLength]] Length of the lineage (default: `1`)

`Snapshot` initializes the <<internal-properties, internal properties>>.

== [[state]] `state` Method

[source, scala]
----
state: Dataset[SingleAction]
----

`state` simply requests the <<cachedState, cached delta state>> to <<CachedDS.adoc#getDS, get the delta state from the cache>>.

NOTE: `state` is used when...FIXME

== [[numIndexedCols]] dataSkippingNumIndexedCols Table Property -- `numIndexedCols` Value

[source, scala]
----
numIndexedCols: Int
----

`numIndexedCols` simply reads the <<DeltaConfigs.adoc#DATA_SKIPPING_NUM_INDEXED_COLS, dataSkippingNumIndexedCols>> table property <<DeltaConfigs.adoc#fromMetaData, from>> the <<metadata, Metadata>>.

NOTE: `numIndexedCols` seems unused.

== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| cachedState
a| [[cachedState]] <<CachedDS.adoc#, CachedDS>>

Used when...FIXME

| metadata
a| [[metadata]] <<Metadata.adoc#, Metadata>> of the <<deltaLog, delta table>>

Used when...FIXME

|===
