= [[TahoeFileIndex]] TahoeFileIndex

`TahoeFileIndex` is an <<contract, extension>> of the Spark SQL `FileIndex` contract for <<implementations, file indices>> that can <<listFiles, list data files>> based on <<matchingFiles, partition and data filters>>.

[[contract]]
.TahoeFileIndex Contract (Abstract Methods Only)
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| matchingFiles
a| [[matchingFiles]]

[source, scala]
----
matchingFiles(
  partitionFilters: Seq[Expression],
  dataFilters: Seq[Expression],
  keepStats: Boolean = false): Seq[AddFile]
----

Matching (valid) files by the given filtering expressions (`partitionFilters` and `dataFilters`)

Used exclusively while <<listFiles, listing data files>>

|===

[[rootPaths]]
When requested for root input paths (`rootPaths`), `TahoeFileIndex` simply gives the <<path, path>>.

[[implementations]]
.TahoeFileIndices
[cols="30,70",options="header",width="100%"]
|===
| TahoeFileIndex
| Description

| <<TahoeBatchFileIndex.adoc#, TahoeBatchFileIndex>>
| [[TahoeBatchFileIndex]]

| <<TahoeLogFileIndex.adoc#, TahoeLogFileIndex>>
| [[TahoeLogFileIndex]]

|===

== [[creating-instance]] Creating TahoeFileIndex Instance

`TahoeFileIndex` takes the following to be created:

* [[spark]] `SparkSession`
* [[deltaLog]] <<DeltaLog.adoc#, DeltaLog>>
* [[path]] Hadoop `Path`

`TahoeFileIndex` initializes the <<internal-properties, internal properties>>.

NOTE: `TahoeFileIndex` is a Scala abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete file indices>>.

== [[tableVersion]] Version of Delta Table -- `tableVersion` Method

[source, scala]
----
tableVersion: Long
----

`tableVersion` is simply the <<Snapshot.adoc#version, version>> of (the <<DeltaLog.adoc#snapshot, snapshot>> of) the <<deltaLog, DeltaLog>>.

NOTE: `tableVersion` is used when `TahoeFileIndex` is requested for a <<toString, human-friendly textual representation>>.

== [[listFiles]] Listing Data Files -- `listFiles` Method

[source, scala]
----
listFiles(
  partitionFilters: Seq[Expression],
  dataFilters: Seq[Expression]): Seq[PartitionDirectory]
----

NOTE: `listFiles` is part of the `FileIndex` contract (Spark SQL) to...FIXME.

`listFiles`...FIXME

== [[toString]] Human-Friendly Textual Representation -- `toString` Method

[source, scala]
----
toString: String
----

NOTE: `toString` is part of the `java.lang.Object` contract for a string representation of the object.

`toString` returns the following text (based on the <<tableVersion, table version>> and the <<path, path>> truncated to 100 characters):

```
Delta[version=[tableVersion], [truncatedPath]]
```
